services:
  postgres:
    image: postgres:17.4-alpine
    container_name: go-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
volumes:
  postgres_data:
